server:
  port: 8081
  context-path: /pos

spring:
  datasource: # Database properties
    url: jdbc:h2:/tmp/cagisterdb
    username: sa
    password:
#    data: classpath:/load-test-data.sql
  jpa: # JPA configuration
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect